version: '3'

services:

  db:
    image: 'postgres:latest'
    container_name: postgres-solemne
    build:
      context: ./postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=remedio
    
    volumes:
      - pg-data:/var/lib/postgresql/data

  
  backendbc:
    image: londresdev/backend:latest
    container_name: backend
    build:
      context: ./backend
    
    ports:
      - "6789:6789"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/remedio
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - db

  frontendbc:
    image: londresdev/frontend:latest
    container_name: frontend
    build:
      context: ./frontend 
    ports:
      - "9876:9876"
    depends_on:
      - db

volumes:
  pg-data:
